app_token = "qq"
name = "QQ"
desc = "Instant messaging tool"
homepage = "https://im.qq.com/macqq/index.shtml"
bundle_id = "com.tencent.qq"

[[sources]]
type = "homebrew"
cask = "qq"

[[sources]]
type = "appstore"
app_id = "451108668"
