app_token = "qview"
name = "qView"
desc = "Image viewer"
homepage = "https://github.com/jurplel/qView/"
bundle_id = "com.interversehq.qView"

[[sources]]
type = "homebrew"
cask = "qview"

[[sources]]
type = "github"
repo = "jurplel/qView"
