app_token = "postman-agent"
name = "Postman Agent"
desc = "Desktop agent for Postman on the Web"
homepage = "https://www.postman.com/downloads/postman-agent/"
bundle_id = "com.postmanlabs.agent.mac"

[[sources]]
type = "homebrew"
cask = "postman-agent"
