app_token = "openlens"
name = "OpenLens"
desc = "Open source build of Lens Kubernetes IDE"
homepage = "https://github.com/MuhammedKalkan/OpenLens/"
bundle_id = "com.electron.open-lens"

[[sources]]
type = "homebrew"
cask = "openlens"

[[sources]]
type = "github"
repo = "MuhammedKalkan/OpenLens"
