app_token = "karing"
name = "Karing"
desc = "Proxy utility"
homepage = "https://karing.app/"
bundle_id = "com.nebula.karing"

[[sources]]
type = "homebrew"
cask = "karing"

[[sources]]
type = "github"
repo = "KaringX/karing"
