app_token = "ksnip"
name = "ksnip"
desc = "Screenshot and annotation tool"
homepage = "https://github.com/ksnip/ksnip"
bundle_id = "org.ksnip.ksnip"

[[sources]]
type = "homebrew"
cask = "ksnip"

[[sources]]
type = "github"
repo = "ksnip/ksnip"
