app_token = "gitx"
name = "GitX"
desc = "Git GUI"
homepage = "https://github.com/gitx/gitx"
bundle_id = "net.phere.GitX"

[[sources]]
type = "homebrew"
cask = "gitx"

[[sources]]
type = "github"
repo = "gitx/gitx"
