app_token = "wireshark-app"
name = "Wireshark"
desc = "Network protocol analyzer"
homepage = "https://www.wireshark.org/"
bundle_id = "org.wireshark.Wireshark"

[[sources]]
type = "homebrew"
cask = "wireshark-app"

[[sources]]
type = "sparkle"
url = "https://www.wireshark.org/update/0/Wireshark/0.0.0/macOS/arm64/en-US/stable.xml"
