app_token = "clop"
name = "Clop"
desc = "Image, video and clipboard optimiser"
homepage = "https://lowtechguys.com/clop/"
bundle_id = "com.lowtechguys.Clop"

[[sources]]
type = "homebrew"
cask = "clop"

[[sources]]
type = "sparkle"
url = "https://files.lowtechguys.com/clop/appcast.xml"
