app_token = "cryptomator"
name = "Cryptomator"
desc = "Multi-platform client-side cloud file encryption tool"
homepage = "https://cryptomator.org/"
bundle_id = "org.cryptomator"

[[sources]]
type = "homebrew"
cask = "cryptomator"

[[sources]]
type = "github"
repo = "cryptomator/cryptomator"
