app_token = "fanny"
name = "FannyWidget"
desc = "Notification Center widget and menu bar application to monitor fans"
homepage = "https://fannywidget.com/"
bundle_id = "com.fannywidget"

[[sources]]
type = "homebrew"
cask = "fanny"

[[sources]]
type = "github"
repo = "DanielStormApps/Fanny"
