app_token = "forecast"
name = "Forecast"
desc = "Podcast MP3 encoder with chapters"
homepage = "https://overcast.fm/forecast"
bundle_id = "fm.overcast.forecast-encoder"

[[sources]]
type = "homebrew"
cask = "forecast"

[[sources]]
type = "sparkle"
url = "https://overcast.fm/appcast/Forecast.xml"
