app_token = "fresh"
name = "Fresh"
desc = "Keep your recently modified files at hand and up-to-date"
homepage = "https://ironicsoftware.com/fresh/"
bundle_id = "com.ironic.fresh4"

[[sources]]
type = "homebrew"
cask = "fresh"

[[sources]]
type = "sparkle"
url = "https://ironicsoftware.com/downloads/fresh4.xml"
