app_token = "via"
name = "VIA"
desc = "Keyboard configurator"
homepage = "https://caniusevia.com/"
bundle_id = "org.via.configurator"

[[sources]]
type = "homebrew"
cask = "via"

[[sources]]
type = "github"
repo = "the-via/releases"
