app_token = "vidl"
name = "ViDL for Mac"
desc = "GUI frontend for youtube-dl"
homepage = "https://omz-software.com/vidl/"
bundle_id = "com.omz-software.ViDL"

[[sources]]
type = "homebrew"
cask = "vidl"

[[sources]]
type = "sparkle"
url = "https://ssl.webpack.de/omz-software.com/vidl/appcast.xml"
