app_token = "jellyfin-media-player"
name = "Jellyfin Media Player"
desc = "Jellyfin desktop client"
homepage = "https://jellyfin.org/"
bundle_id = "tv.jellyfin.player"

[[sources]]
type = "homebrew"
cask = "jellyfin-media-player"

[[sources]]
type = "github"
repo = "jellyfin/jellyfin-media-player"
