app_token = "jettison"
name = "Jettison"
desc = "Automatically ejects external drives"
homepage = "https://stclairsoft.com/Jettison/"
bundle_id = "com.stclairsoft.Jettison"

[[sources]]
type = "homebrew"
cask = "jettison"

[[sources]]
type = "sparkle"
url = "https://stclairsoft.com/cgi-bin/sparkle.cgi?JT"
