app_token = "jottacloud"
name = "Jottacloud"
desc = "Client for the Jottacloud cloud storage service"
homepage = "https://jottacloud.com/"
bundle_id = "no.jotta.Jottacloud"

[[sources]]
type = "homebrew"
cask = "jottacloud"

[[sources]]
type = "sparkle"
url = "https://sw.jotta.cloud/desktop/appcast/CUST/release"
