app_token = "reactotron"
name = "Reactotron"
desc = "Desktop app for inspecting React JS and React Native projects"
homepage = "https://github.com/infinitered/reactotron"
bundle_id = "com.reactotron.app"

[[sources]]
type = "homebrew"
cask = "reactotron"

[[sources]]
type = "github"
repo = "infinitered/reactotron"
regex = '^Reactotron-(\d+\.\d+\.\d+)-arm64\.dmg$'
