app_token = "tabby"
name = "Tabby"
desc = "Terminal emulator, SSH and serial client"
homepage = "https://eugeny.github.io/tabby/"
bundle_id = "org.tabby"

[[sources]]
type = "homebrew"
cask = "tabby"

[[sources]]
type = "github"
repo = "Eugeny/tabby"
