app_token = "texstudio"
name = "TeXstudio"
desc = "LaTeX editor"
homepage = "https://texstudio.org/"
bundle_id = "texstudio"

[[sources]]
type = "homebrew"
cask = "texstudio"

[[sources]]
type = "github"
repo = "texstudio-org/texstudio"
