app_token = "simple-comic"
name = "Simple Comic"
desc = "Comic viewer/reader"
homepage = "https://github.com/MaddTheSane/Simple-Comic"
bundle_id = "com.ToWatchList.SimpleComic"

[[sources]]
type = "homebrew"
cask = "simple-comic"

[[sources]]
type = "github"
repo = "MaddTheSane/Simple-Comic"
