app_token = "submariner"
name = "Submariner"
desc = "Subsonic client"
homepage = "https://submarinerapp.com/"
bundle_id = "fr.read-write.Submariner"

[[sources]]
type = "homebrew"
cask = "submariner"

[[sources]]
type = "github"
repo = "NattyNarwhal/Submariner"
