app_token = "macvim-app"
name = "MacVim"
desc = "GUI for vim, made for macOS"
homepage = "https://macvim.org/"
bundle_id = "org.vim.MacVim"

[[sources]]
type = "homebrew"
cask = "macvim-app"

[[sources]]
type = "github"
repo = "macvim-dev/macvim"
