app_token = "marta"
name = "Marta File Manager"
desc = "Extensible two-pane file manager"
homepage = "https://marta.sh/"
bundle_id = "org.yanex.marta"

[[sources]]
type = "homebrew"
cask = "marta"

[[sources]]
type = "sparkle"
url = "https://updates.marta.sh/release/appcast.xml"
