app_token = "mediaelch"
name = "MediaElch"
desc = "Media Manager for Kodi"
homepage = "https://www.kvibes.de/en/mediaelch/"
bundle_id = "com.kvibes.MediaElch"

[[sources]]
type = "homebrew"
cask = "mediaelch"

[[sources]]
type = "github"
repo = "Komet/MediaElch"
