app_token = "microsoft-edge@canary"
name = "Microsoft Edge Canary"
desc = "Multi-platform web browser"
homepage = "https://www.microsoft.com/en-us/edge?form="

[[sources]]
type = "homebrew"
cask = "microsoft-edge@canary"
