app_token = "milkman"
name = "Milkman"
desc = "Extensible request and response workbench"
homepage = "https://github.com/warmuuh/milkman"
bundle_id = "milkman"

[[sources]]
type = "homebrew"
cask = "milkman"

[[sources]]
type = "github"
repo = "warmuuh/milkman"
regex = 'milkman-dist-appbundle-macos64-bin.tgz'
