app_token = "music-decoy"
name = "Music Decoy"
desc = "Music app blocker utility"
homepage = "https://lowtechguys.com/musicdecoy"
bundle_id = "com.apple.Music"

[[sources]]
type = "homebrew"
cask = "music-decoy"

[[sources]]
type = "github"
repo = "FuzzyIdeas/MusicDecoy"
