app_token = "altar-ai"
name = "Altar AI"
desc = "AI-powered meeting assistant"
homepage = "https://app.altar.inc/"

[[sources]]
type = "homebrew"
cask = "altar-ai"

[[sources]]
type = "electron"
url = "https://altar-prototype.sgp1.cdn.digitaloceanspaces.com/latest/latest-mac.yml"
