app_token = "amd-power-gadget"
name = "AMD Power Gadget"
desc = "Power management, monitoring and VirtualSMC plugin for AMD processors"
homepage = "https://github.com/trulyspinach/SMCAMDProcessor"
bundle_id = "wtf.spinach.AMD-Power-Gadget"

[[sources]]
type = "homebrew"
cask = "amd-power-gadget"

[[sources]]
type = "github"
repo = "trulyspinach/SMCAMDProcessor"
