app_token = "aqua-voice"
name = "Aqua Voice"
desc = "Speech-to-text system"
homepage = "https://withaqua.com/"
bundle_id = "com.electron.aqua-voice"

[[sources]]
type = "homebrew"
cask = "aqua-voice"
