app_token = "nagstamon"
name = "Nagstamon"
desc = "Nagios status monitor"
homepage = "https://nagstamon.de/"
bundle_id = "de.nagstamon"

[[sources]]
type = "homebrew"
cask = "nagstamon"

[[sources]]
type = "github"
repo = "HenriWahl/Nagstamon"
