app_token = "notion-calendar"
name = "Notion Calendar"
desc = "Calendar for professionals and teams"
homepage = "https://www.notion.com/product/calendar"
bundle_id = "com.cron.electron"

[[sources]]
type = "homebrew"
cask = "notion-calendar"

[[sources]]
type = "electron"
url = "https://calendar-desktop-release.notion-static.com/latest-mac.yml"
