app_token = "latexit"
name = "LaTeXiT"
desc = "Graphical interface for LaTeX"
homepage = "https://www.chachatelier.fr/latexit/"
bundle_id = "fr.chachatelier.pierre.LaTeXiT"

[[sources]]
type = "homebrew"
cask = "latexit"

[[sources]]
type = "sparkle"
url = "https://pierre.chachatelier.fr/latexit/downloads/latexit-sparkle-en.rss"
