app_token = "leapp"
name = "Leapp"
desc = "Cloud credentials manager"
homepage = "https://www.leapp.cloud/"
bundle_id = "com.leapp.app"

[[sources]]
type = "homebrew"
cask = "leapp"

[[sources]]
type = "electron"
url = "https://asset.noovolari.com/latest/latest-mac.yml"
