app_token = "luanti"
name = "Luanti"
desc = "Voxel game-creation platform"
homepage = "https://www.luanti.org/"
bundle_id = "org.luanti.luanti"

[[sources]]
type = "homebrew"
cask = "luanti"

[[sources]]
type = "github"
repo = "minetest/minetest"
regex = '^luanti_(\d+(?:\.\d+)*)-macos.+\.zip$'
version = "{match[1]}"
