app_token = "heynote"
name = "Heynote"
desc = "Dedicated scratchpad for developers"
homepage = "https://heynote.com/"
bundle_id = "com.heynote.app"

[[sources]]
type = "homebrew"
cask = "heynote"

[[sources]]
type = "github"
repo = "heyman/heynote"
