app_token = "bettermouse"
name = "BetterMouse"
desc = "Utility improving 3rd party mouse performance and functionalities"
homepage = "https://better-mouse.com/"
bundle_id = "com.naotanhaocan.BetterMouse"

[[sources]]
type = "homebrew"
cask = "bettermouse"

[[sources]]
type = "sparkle"
url = "https://better-mouse.com/wp-content/uploads/appcast.xml"
