app_token = "bettershot"
name = "Better Shot"
desc = "Screen capturing and editing tool"
homepage = "https://bettershot.site/"
bundle_id = "com.kartiklabhshetwar.bettershot"

[[sources]]
type = "homebrew"
cask = "bettershot"

[[sources]]
type = "github"
repo = "KartikLabhshetwar/better-shot"
